### ISSUE TITLE
why not use toml (or some other config file) instead of environment variables?

### ISSUE THREAD

**Issue by A1ex-N** [hungrybluedev/klonol#1]
Instead of using a .env file, why not just use a toml file? That way it'd be the same process for windows and linux. Do environment variables have an advantage over just a plain toml file?

**Comment by hungrybluedev** [comment]
That's an excellent suggestion!

I like TOML files because V has a good module supporting them. It'll also be cross-platform. I was using `.env` files because it's easy to source them. We can just have an automatic detection step for nearby files or add a switch to point to one.

If you're up for it, can you contribute to the project?

**Comment by A1ex-N** [comment]
> That's an excellent suggestion!
> 
> I like TOML files because V has a good module supporting them. It'll also be cross-platform. I was using `.env` files because it's easy to source them. We can just have an automatic detection step for nearby files or add a switch to point to one.
> 
> If you're up for it, can you contribute to the project?

Yeah I'd like to contribute to the project. I'll start working on it tomorrow (it's night time for me right now)

**Comment by hungrybluedev** [comment]
Completed via #2
